name: Security

on:
  schedule:
    # Run security checks daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: |
        echo "Running npm security audit..."
        npm audit --audit-level moderate
        continue-on-error: true
    
    - name: Check for outdated packages
      run: |
        echo "Checking for outdated packages..."
        npm outdated || true
    
    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
      continue-on-error: true
    
    - name: Check for secrets in code
      run: |
        echo "Checking for potential secrets in code..."
        # Basic check for common secret patterns
        if grep -r -i "password\|secret\|key\|token\|api_key" . \
          --exclude-dir=node_modules \
          --exclude-dir=.git \
          --exclude-dir=.github \
          --exclude=*.log; then
          echo "Warning: Potential secrets found in code"
        else
          echo "No obvious secrets found in code"
        fi
    
    - name: Check for sensitive files
      run: |
        echo "Checking for sensitive files..."
        sensitive_files=()
        
        if [ -f ".okta.env" ]; then
          sensitive_files+=(".okta.env")
        fi
        
        if [ -f ".env" ]; then
          sensitive_files+=(".env")
        fi
        
        if [ -f "config.json" ]; then
          sensitive_files+=("config.json")
        fi
        
        if [ ${#sensitive_files[@]} -ne 0 ]; then
          echo "Warning: Sensitive files found: ${sensitive_files[*]}"
          echo "Ensure these files are in .gitignore"
        else
          echo "No sensitive files found"
        fi

  dependency-update:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for updates
      run: |
        echo "Checking for available dependency updates..."
        npm outdated || true
    
    - name: Create Dependabot PR
      run: |
        echo "Creating dependency update PR..."
        # This would typically be handled by Dependabot
        # but you can add custom logic here if needed

  code-scanning:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:javascript" 